import {
	Attachment,
	DiscordMessage,
	Embed, MessageActivity, MessageCall,
	MessageReference,
	MessageTypes, Poll,
	Reaction, ResolvedData, RoleSubscriptionData, SharedClientTheme, StickerItem
} from "../Types/MessageComponents.js";
import { APIClientStructure } from "../Contracts/DiscordStructure.js";
import { DiscordApplication, DiscordChannel, DiscordSticker } from "../Types/DiscordAPITypes.js";
import { ObjectValues } from "../Types/HelperTypes.js";
import { Client } from "../Client.js";
import { User } from "./User.js";
import { MessagePayload } from "../Types/Internal.js";
import { Emoji } from "./Emoji.js";
import { Guild } from "./Guild.js";
import { MessageableChannel } from "../Types/index.js";

/**
 * Normalizes user input into a valid message payload.
 * @param input Either plain text content or a full message payload.
 * @returns A payload that can be sent to the Discord messages endpoint.
 * @throws {Error} When no message content, embeds, components, or stickers are provided.
 */
export function CreateMessagePayload(input: string | MessagePayload): MessagePayload {
	if (typeof input === "string") input = { content: input };

	const hasContent: boolean =
		(input.content?.length ?? 0) > 0 ||
		(input.embeds?.length ?? 0) > 0 ||
		(input.components?.length ?? 0) > 0 ||
		(input.sticker_ids?.length ?? 0) > 0

	if (!hasContent) throw new Error("Cannot send an empty message");

	return input;
}

/**
 * A message sent in a text-based channel.
 *
 * @see https://docs.discord.com/developers/resources/message#message-object
 */
export class Message extends APIClientStructure<DiscordMessage> {
	id!: string
	channelId!: string
	/** Id of the guild this message was sent in, only present on gateway payloads (`MESSAGE_CREATE` etc.), not in the Discord message object itself */
	guildId?: string | null
	/**
	 * Raw partial guild member object for the message author, only present on gateway payloads
	 * and not otherwise parsed into a {@link Member}. Typed `unknown` because no consumer in
	 * this codebase reads it yet — treat it as an opaque `DiscordMember`-shaped object if you
	 * need to use it.
	 */
	member: unknown | null
	/** The message author. Named `user` here instead of Discord's `author`; not guaranteed to be a valid user for messages generated by webhooks or the system */
	user!: User
	content!: string
	timestamp!: string
	/** ISO timestamp of the last edit, or `null` if the message was never edited */
	editedTimestamp!: string | null
	tts!: boolean
	mentionEveryone!: boolean
	mentions!: User[]
	mentionRoles!: string[]
	/** Partial channel objects for channels specifically mentioned in this message */
	mentionChannels?: unknown[]
	attachments!: Attachment[]
	embeds!: Embed[]
	reactions?: Reaction[]
	/** Value used by the client to verify the message it sent was received by the API, not a stable identifier */
	nonce?: number | string
	pinned!: boolean
	/** Id of the webhook that generated this message, only present for webhook messages */
	webhookId?: string
	type!: ObjectValues<typeof MessageTypes>
	/** Rich Presence activity data, sent with invite-to-game/spectate chat embeds */
	activity?: MessageActivity
	/** Rich Presence application data, sent alongside `activity` */
	application?: Partial<DiscordApplication>
	/** Id of the application that sent this message, present when the message is an interaction response or an application-owned webhook message */
	applicationId?: string
	/** Message flags bitfield (e.g. `CROSSPOSTED`, `EPHEMERAL`, `SUPPRESS_NOTIFICATIONS`) */
	flags?: number
	/** Reference data identifying the source message for a reply, crosspost, forward, or channel-follow-add */
	messageReference?: MessageReference
	/** For forwarded messages, a minimal snapshot of the forwarded message (author is excluded) */
	messageSnapshots?: { message: Partial<DiscordMessage> }[]
	/** The message pointed to by `messageReference`, or `null` if it has since been deleted */
	referencedMessage?: DiscordMessage | null
	/** Metadata about the interaction that produced this message, if any */
	interactionMetadata?: unknown
	/** @deprecated Superseded by `interactionMetadata`; the interaction this message was a response to */
	interaction?: unknown
	/** The thread that was started from this message, if any */
	thread?: DiscordChannel
	/** Message components (buttons, action rows, etc.) attached to this message */
	components?: unknown[]
	/** Lightweight sticker references (id, name, format) sent with the message */
	stickerItems?: StickerItem[]
	/** @deprecated Full sticker objects sent with the message; superseded by `stickerItems` */
	stickers?: DiscordSticker[]
	/** Generally-increasing (may contain gaps or duplicates) approximate position of this message within its thread, usable alongside the parent thread's `total_message_sent` */
	position?: number
	/** Data about the role subscription purchase/renewal that triggered a `ROLE_SUBSCRIPTION_PURCHASE` message */
	roleSubscriptionData?: RoleSubscriptionData
	/** Users, members, channels, and roles referenced by this message, resolved for interaction responses */
	resolved?: ResolvedData
	poll?: Poll
	/** Data for the voice/video call this message represents (`type` `CALL`) */
	call?: MessageCall
	/** Custom client-side theme shared via this message */
	sharedClientTheme?: SharedClientTheme

	constructor(client: Client, data: DiscordMessage & { guild_id?: string | null; member?: unknown | null }) {
		super(client);
		this.patch(data);
	}

	patch(data: DiscordMessage & { guild_id?: string | null; member?: unknown | null }): void {
		this.id = data.id;
		this.channelId = data.channel_id;
		this.user = this.client.users.upsert(data.author);
		this.content = data.content;
		this.timestamp = data.timestamp;
		this.editedTimestamp = data.edited_timestamp;
		this.tts = data.tts;
		this.mentionEveryone = data.mention_everyone;
		this.mentionRoles = data.mention_roles;
		this.attachments = data.attachments;
		this.embeds = data.embeds;
		this.pinned = data.pinned;
		this.type = data.type;

		const mentionUsers = [];
		for (const user of data.mentions) {
			mentionUsers.push( this.client.users.upsert(user) );
		}
		this.mentions = mentionUsers;

		if ("mention_channels" in data && data.mention_channels !== undefined) this.mentionChannels = data.mention_channels;
		if ("reactions" in data && data.reactions !== undefined) this.reactions = data.reactions;
		if ("nonce" in data && data.nonce !== undefined) this.nonce = data.nonce;
		if ("webhook_id" in data && data.webhook_id !== undefined) this.webhookId = data.webhook_id;
		if ("activity" in data && data.activity !== undefined) this.activity = data.activity;
		if ("application" in data && data.application !== undefined) this.application = data.application;
		if ("application_id" in data && data.application_id !== undefined) this.applicationId = data.application_id;
		if ("flags" in data && data.flags !== undefined) this.flags = data.flags;
		if ("message_reference" in data && data.message_reference !== undefined) this.messageReference = data.message_reference;
		if ("message_snapshots" in data && data.message_snapshots !== undefined) this.messageSnapshots = data.message_snapshots;
		if ("referenced_message" in data && data.referenced_message !== undefined) this.referencedMessage = data.referenced_message;
		if ("interaction_metadata" in data && data.interaction_metadata !== undefined) this.interactionMetadata = data.interaction_metadata;
		if ("interaction" in data && data.interaction !== undefined) this.interaction = data.interaction;
		if ("thread" in data && data.thread !== undefined) this.thread = data.thread;
		if ("components" in data && data.components !== undefined) this.components = data.components;
		if ("sticker_items" in data && data.sticker_items !== undefined) this.stickerItems = data.sticker_items;
		if ("stickers" in data && data.stickers !== undefined) this.stickers = data.stickers;
		if ("position" in data && data.position !== undefined) this.position = data.position;
		if ("role_subscription_data" in data && data.role_subscription_data !== undefined) this.roleSubscriptionData = data.role_subscription_data;
		if ("resolved" in data && data.resolved !== undefined) this.resolved = data.resolved;
		if ("poll" in data && data.poll !== undefined) this.poll = data.poll;
		if ("call" in data && data.call !== undefined) this.call = data.call;
		if ("shared_client_theme" in data && data.shared_client_theme !== undefined) this.sharedClientTheme = data.shared_client_theme;

		if ("guild_id" in data) this.guildId = data.guild_id;
		if ("member" in data) this.member = data.member;
	}

	/**
	 * A smart getter that reads the guild from cache on first read and overwrites itself on consecutive reads
	 */
	get guild(): Guild | null {
		const value = this.client.guilds.get(this.guildId!) ?? null;
		Object.defineProperty(this, 'guild', {
			value: value
		});
		return value;
	}

	/**
	 * A smart getter that reads the channel (and guild) from cache on first read and overwrites itself on consecutive reads
	 */
	// physically impossible for a message to be sent in a category lmao
	get channel(): MessageableChannel | null {
		const value = (this.guild?.channels.get(this.channelId) ?? null) as MessageableChannel | null;
		Object.defineProperty(this, 'channel', {
			value: value
		});
		return value;
	}

	/**
	 * Sends a reply to this message.
	 * @param content Either plain text content or a full message payload.
	 * @param options Reply behavior options.
	 * @returns The created reply message.
	 */
	async reply(content: string | MessagePayload, options: { ping?: boolean } = {}): Promise<Message> {
		const payload = CreateMessagePayload(content);
		payload.message_reference = {
			message_id: this.id
		}
		if (!options.ping) {
			payload.allowed_mentions ??= {};
			payload.allowed_mentions.replied_user ??= false
		}
		const response = await this.client.rest.post<DiscordMessage>(`/channels/${this.channelId}/messages`, payload);
		return new Message(this.client, response);
	}

	/**
	 * Deletes a message. Requires the `MANAGE_MESSAGES` permission and will error otherwise.
	 */
	async delete(): Promise<void> {
		return await this.client.rest.delete(`/channels/${this.channelId}/messages/${this.id}`);
	}

	/**
	 * Edits this message.
	 *
	 * Only messages authored by the current bot user can be updated.
	 * @param content Updated message content or payload.
	 * @returns The updated message.
	 * @throws {Error} When attempting to edit a message not authored by the bot.
	 */
	async update(content: string | Omit<MessagePayload, 'sticker_ids' | 'message_reference'>): Promise<Message> {
		if (this.user.id !== this.client.user!.id) throw new Error("Can only edit messages sent by the bot");
		const payload = CreateMessagePayload(content);
		const response = await this.client.rest.patch<DiscordMessage>(`/channels/${this.channelId}/messages/${this.id}`, payload);
		return new Message(this.client, response);
	}

	/**
	 * Pins this message in its channel.
	 */
	async pin(): Promise<void> {
		await this.client.rest.put(`/channels/${this.channelId}/messages/pins/${this.id}`, null);
	}

	/**
	 * Removes this message from channel pins.
	 */
	async unpin(): Promise<void> {
		await this.client.rest.delete(`/channels/${this.channelId}/messages/pins/${this.id}`);
	}

	/**
	 * Add a reaction to the message as the bot
	 * @example
	 * ```ts
	 * await message.react('😀');
	 * await message.react(guild.emojis.get('1234567890'));
	 * await message.react({ id: "1234567890", name: "RainbowFrogDance" });
	 * ```
	 */
	async react(input: string | Emoji | {id: string, name: string}): Promise<void> {
		let encodedEmoji: string;
		if (typeof input === 'string') {
			encodedEmoji = encodeURIComponent(input);
		} else {
			encodedEmoji = `${encodeURIComponent(input.name)}:${input.id}`;
		}
		await this.client.rest.put(`/channels/${this.channelId}/messages/${this.id}/reactions/${encodedEmoji}/@me`, null)
	}
}